= sfl::small_flat_multimap
:last-update-label!:
:stylesheet: stylesheet.css
:toc:

== Summary

Defined in header `<sfl/small_flat_multimap.hpp>`.

----
namespace sfl
{

template < typename Key,
           typename T,
           std::size_t N,
           typename Compare = std::less<Key>,
           typename Allocator = std::allocator<std::pair<Key, T>> >
class small_flat_multimap;

}
----

`sfl::small_flat_multimap` is a sorted associative container similar
to `std::multimap`.
It contains sorted key-value pairs, while permitting multiple entries with the same key.
Sorting is done according to the comparison function `Compare`, applied to the keys.

Unlike `std::multimap`, the elements are stored contiguously in the memory.
That means that iterators to the elements are random access iterators.
The storage is handled automatically, being expanded and contracted as needed.
`sfl::small_flat_multimap` holds statically allocated array of size `N` in
the object itself.
The container stores elements into this array until number of elements is not
greater than `N`, which avoids dynamic memory allocation and deallocation.
The dynamic memory management is used when the number of elements has to be
greater than `N`.
The size `N` is specified at the compile time as a template parameter.
In case when `N` is equal to zero the container does not hold any statically
allocated array and uses only dynamic memory management.

`sfl::small_flat_multimap` meets the requirements of
https://en.cppreference.com/w/cpp/named_req/Container[`Container`],
https://en.cppreference.com/w/cpp/named_req/AllocatorAwareContainer[`AllocatorAwareContainer`],
https://en.cppreference.com/w/cpp/named_req/ReversibleContainer[`ReversibleContainer`],
https://en.cppreference.com/w/cpp/named_req/ContiguousContainer[`ContiguousContainer`] and
https://en.cppreference.com/w/cpp/named_req/AssociativeContainer[`AssociativeContainer`].

{empty} +

== Template parameters

. `typename Key`
+
Key type.

. `typename T`
+
Value type.

. `std::size_t N`
+
Size of the internal statically allocated array. This parameter can be zero.

. `typename Compare`
+
Ordering function for keys.

. `typename Allocator`
+
Allocator used for memory allocation/deallocation and construction/destruction
of elements.
This type must meet the requirements of
https://en.cppreference.com/w/cpp/named_req/Allocator[`Allocator`].
The program is ill-formed if `Allocator::value_type` is not the same as
`std::pair<Key, T>`.

{empty} +

== Member types

----
using allocator_type         = Allocator;
using allocator_traits       = std::allocator_traits<allocator_type>;
using key_type               = Key;
using mapped_type            = T;
using value_type             = std::pair<Key, T>;
using size_type              = typename allocator_traits::size_type;
using difference_type        = typename allocator_traits::difference_type;
using key_compare            = Compare;
using reference              = value_type&;
using const_reference        = const value_type&;
using pointer                = typename allocator_traits::pointer;
using const_pointer          = typename allocator_traits::const_pointer;
using iterator               = pointer;
using const_iterator         = const_pointer;
using reverse_iterator       = std::reverse_iterator<iterator>;
using const_reverse_iterator = std::reverse_iterator<const_iterator>;

class value_compare
{
public:
    bool operator()(const value_type& x, const value_type& y) const;
};
----

{empty} +

== Member functions

=== (constructor)

----
small_flat_multimap() noexcept(
    std::is_nothrow_default_constructible<Allocator>::value &&
    std::is_nothrow_default_constructible<Compare>::value
);
explicit small_flat_multimap(const Compare& comp) noexcept(
    std::is_nothrow_default_constructible<Allocator>::value &&
    std::is_nothrow_copy_constructible<Compare>::value
);
explicit small_flat_multimap(const Allocator& alloc) noexcept(
    std::is_nothrow_copy_constructible<Allocator>::value &&
    std::is_nothrow_default_constructible<Compare>::value
);
explicit small_flat_multimap(const Compare& comp, const Allocator& alloc) noexcept(
    std::is_nothrow_copy_constructible<Allocator>::value &&
    std::is_nothrow_copy_constructible<Compare>::value
);
----
{empty} ::
+
--
*Effects:*
Constructs an empty container.

*Complexity:*
Constant.
--

{empty} +

----
template <typename InputIt>
  small_flat_multimap(InputIt first, InputIt last);
template <typename InputIt>
  small_flat_multimap(InputIt first, InputIt last, const Compare& comp);
template <typename InputIt>
  small_flat_multimap(InputIt first, InputIt last, const Allocator& alloc);
template <typename InputIt>
  small_flat_multimap(InputIt first, InputIt last, const Compare& comp,
                                                   const Allocator& alloc);
----
{empty} ::
+
--
*Effects:*
Constructs an empty container and inserts elements from the range
`[first, last)`.

*Note:*
This overload participates in overload resolution only if `InputIt`
satisfies requirements of
https://en.cppreference.com/w/cpp/named_req/InputIterator[`LegacyInputIterator`].

*Complexity:*
Linear in `std::distance(first, last)`.
--

{empty} +

----
small_flat_multimap(std::initializer_list<value_type> ilist);
small_flat_multimap(std::initializer_list<value_type> ilist,
                    const Compare& comp);
small_flat_multimap(std::initializer_list<value_type> ilist,
                    const Allocator& alloc);
small_flat_multimap(std::initializer_list<value_type> ilist,
                    const Compare& comp, const Allocator& alloc);
----
{empty} ::
+
--
*Effects:*
Constructs an empty container and inserts elements from the initializer
list `ilist`.

*Complexity:*
Linear in `ilist.size()`.
--

{empty} +

----
small_flat_multimap(const small_flat_multimap& other);
small_flat_multimap(const small_flat_multimap& other, const Allocator& alloc);
----
{empty} ::
+
--
*Effects:*
Constructs the container with the copy of the contents of `other`.

*Complexity:*
Linear in `other.size()`.
--

{empty} +

----
small_flat_multimap(small_flat_multimap&& other);
small_flat_multimap(small_flat_multimap&& other, const Allocator& alloc);
----
{empty} ::
+
--
*Effects:*
Constructs the container with the contents of `other` using move semantics.
`other` is not guaranteed to be empty after the move.
`other` is in a valid but unspecified state after the move.

*Complexity:*
Constant in the best case. Linear in `N` in the worst case.
--

{empty} +

=== (destructor)

----
~small_flat_multimap();
----
{empty} ::
+
--
*Effects:*
Destructs the container. The destructors of the elements are called and
the used storage is deallocated.

*Complexity:*
Linear in `size()`.
--

{empty} +

=== operator=

----
small_flat_multimap& operator=(const small_flat_multimap& other);
----
{empty} ::
+
--
*Effects:*
Copy assignment operator. Replaces the contents with a copy of the contents
of `other`.

*Returns:*
`*this()`.

*Complexity:*
Linear in `+this->size()+` plus linear in `+other.size()+`.
--

{empty} +

----
small_flat_multimap& operator=(small_flat_multimap&& other);
----
{empty} ::
+
--
*Effects:*
Move assignment operator.
Replaces the contents with those of `other` using move semantics.
`other` is not guaranteed to be empty after the move.
`other` is in a valid but unspecified state after the move.

*Returns:*
`*this()`.

*Complexity:*

* The best case: Linear in `+this->size()+` plus constant.
* The worst case: Linear in `+this->size()+` plus linear in `+other.size()+`.
--

{empty} +

----
small_flat_multimap& operator=(std::initializer_list<value_type> ilist);
----
{empty} ::
+
--
*Effects:*
Replaces the contents with those identified by initializer list `ilist`.

*Returns:*
`*this()`.

*Complexity:*
Linear in `+this->size()+` plus linear in `+ilist.size()+`.
--

{empty} +

=== get_allocator

----
allocator_type get_allocator() const noexcept;
----
{empty} ::
+
--
*Effects:*
Returns the allocator associated with the container.

*Complexity:*
Constant.
--

{empty} +

=== key_comp

----
key_compare key_comp() const;
----
{empty} ::
+
--
*Effects:*
Returns the function object that compares the keys, which is a copy of
this container's constructor argument `comp`.

*Complexity:*
Constant.
--

{empty} +

=== value_comp

----
value_compare value_comp() const;
----
{empty} ::
+
--
*Effects:*
Returns a function object that compares objects of type `value_type`.

*Complexity:*
Constant.
--

{empty} +

=== begin, cbegin

----
iterator       begin() noexcept;
const_iterator begin() const noexcept;
const_iterator cbegin() const noexcept;
----
{empty} ::
+
--
*Effects:*
Returns an iterator to the first element of the container.
If the container is empty, the returned iterator is equal to `end()`.

*Complexity:*
Constant.
--

{empty} +

=== end, cend

----
iterator       end() noexcept;
const_iterator end() const noexcept;
const_iterator cend() const noexcept;
----
{empty} ::
+
--
*Effects:*
Returns an iterator to the element following the last element of
the container. This element acts as a placeholder, attempting to
access it results in undefined behavior.

*Complexity:*
Constant.
--

{empty} +

=== rbegin, crbegin

----
reverse_iterator       rbegin() noexcept;
const_reverse_iterator rbegin() const noexcept;
const_reverse_iterator crbegin() const noexcept;
----
{empty} ::
+
--
*Effects:*
Returns a reverse iterator to the first element of the reversed container.
It corresponds to the last element of the non-reversed containers.
If the container is empty, the returned iterator is equal to `rend()`.

*Complexity:*
Constant.
--

{empty} +

=== rend, crend

----
reverse_iterator       rend() noexcept;
const_reverse_iterator rend() const noexcept;
const_reverse_iterator crend() const noexcept;
----
{empty} ::
+
--
*Effects:*
Returns a reverse iterator to the element following the last element of
the reversed container. It corresponds to the element preceding the first
element of the non-reversed container. This element acts as a placeholder,
attempting to access it results in undefined behavior.

*Complexity:*
Constant.
--

{empty} +

=== nth

----
iterator       nth(size_type pos) noexcept;
const_iterator nth(size_type pos) const noexcept;
----
{empty} ::
+
--
*Preconditions:*
`+pos <= size()+`.

*Effects:*
Returns an iterator to the element at position `pos`.
If `+pos == size()+`, the returned iterator is equal to `end()`.

*Complexity:*
Constant.
--

{empty} +

=== index_of

----
size_type index_of(const_iterator pos) const noexcept;
----
{empty} ::
+
--
*Preconditions:*
`+cbegin() <= pos && pos <= cend()+`.

*Effects:*
Returns position of the element pointed by iterator `pos`.
If `+pos == end()+`, the returned value is equal to `size()`.

*Complexity:*
Constant.
--

{empty} +

=== empty

----
bool empty() const noexcept;
----
{empty} ::
+
--
*Effects:*
Returns `true` if the container has no elements,
i.e. whether `+begin() == end()+`.

*Complexity:*
Constant.
--

{empty} +

=== size

----
size_type size() const noexcept;
----
{empty} ::
+
--
*Effects:*
Returns the number of elements in the container,
i.e. `+std::distance(begin(), end())+`.

*Complexity:*
Constant.
--

{empty} +

=== max_size

----
size_type max_size() const noexcept;
----
{empty} ::
+
--
*Effects:*
Returns the maximum number of elements the container is able to hold,
i.e. `+std::distance(begin(), end())+` for the largest container.

*Complexity:*
Constant.
--

{empty} +

=== capacity

----
size_type capacity() const noexcept;
----
{empty} ::
+
--
*Effects:*
Returns the number of elements that the container has currently
allocated space for.

*Complexity:*
Constant.
--

{empty} +

=== reserve

----
void reserve(size_type new_cap);
----
{empty} ::
+
--
*Effects:*
Tries to increase capacity by allocating additional memory.

. If `+new_cap > capacity()+`, the function allocates memory for new storage
of capacity equal to the value of `new_cap`, moves elements from old storage
to new storage, and deallocates memory used by old storage.

. Otherwise the function does nothing.

This function does not change size of the container.

If the capacity is changed, all iterators and all references to the elements
are invalidated. Otherwise, no iterators or references are invalidated.

*Complexity:*
Linear.

*Exceptions:*

* `Allocator::allocate` may throw.
* ``T``'s move or copy constructor may throw.

If an exception is thrown:

* If type `T` has available `noexcept` move constructor:
** This function has no effects (strong exception guarantee).
* Else if type `T` has available copy constructor:
** This function has no effects (strong exception guarantee).
* Else if type `T` has available throwing move constructor:
** Container is changed but in valid state (basic exception guarantee).
--

{empty} +

=== shrink_to_fit

----
void shrink_to_fit();
----
{empty} ::
+
--
*Effects:*
Tries to reduce memory usage by freeing unused memory.

. If `+size() > N && size() < capacity()+`, the function allocates memory for
new storage of capacity equal to the value of `size()`, moves elements from
old storage to new storage, and deallocates memory used by old storage.

. If `+size() <= N && N < capacity()+`, the function sets new storage to be
internal statically allocated array of capacity `N`, moves elements from
old storage to new storage, and deallocates memory used by old storage.

. Otherwise the function does nothing.

This function does not change size of the container.

If the capacity is changed, all iterators and all references to the elements
are invalidated. Otherwise, no iterators or references are invalidated.

*Complexity:*
Linear.

*Exceptions:*

* `Allocator::allocate` may throw.
* ``T``'s move or copy constructor may throw.

If an exception is thrown:

* If type `T` has available `noexcept` move constructor:
** This function has no effects (strong exception guarantee).
* Else if type `T` has available copy constructor:
** This function has no effects (strong exception guarantee).
* Else if type `T` has available throwing move constructor:
** Container is changed but in valid state (basic exception guarantee).
--

{empty} +

=== clear

----
void clear() noexcept;
----
{empty} ::
+
--
*Effects:*
Erases all elements from the container.
After this call, `size()` returns zero and `capacity()` remains unchanged.

*Complexity:*
Linear in `size()`.
--

{empty} +

=== emplace

----
template <typename... Args>
iterator emplace(Args&&... args);
----
{empty} ::
+
--
*Effects:*
Inserts a new element into the container.
New element is constructed as `+value_type(std::forward<Args>(args)...)+`.

*Returns:*
Returns an iterator to the inserted element.
--

{empty} +

=== emplace_hint

----
template <typename... Args>
iterator emplace_hint(const_iterator hint, Args&&... args);
----
{empty} ::
+
--
*Preconditions:*
`+cbegin() <= hint && hint <= cend()+`.

*Effects:*
Inserts a new element into the container.
New element is constructed as `+value_type(std::forward<Args>(args)...)+`.
Iterator `hint` is used as a suggestion where to start to search insert
position.

*Returns:*
Returns an iterator to the inserted element.
--

{empty} +

=== insert

----
iterator insert(const value_type& value);
----
{empty} ::
+
--
*Effects:*
Inserts copy of `value`.

*Returns:*
Returns an iterator to the inserted element.
--

{empty} +

----
iterator insert(value_type&& value);
----
{empty} ::
+
--
*Effects:*
Inserts `value` using move semantics.

*Returns:*
Returns an iterator to the inserted element.
--

{empty} +

----
template <typename P>
iterator insert(P&& value);
----
{empty} ::
+
--
*Effects:*
Inserts a new element into the container.
New element is constructed as `+value_type(std::forward<P>(value))+`.

*Note:*
This overload participates in overload resolution only if
`+std::is_constructible<value_type, P&&>::value+` is `true`.

*Returns:*
Returns an iterator to the inserted element.
--

{empty} +

----
iterator insert(const_iterator hint, const value_type& value);
----
{empty} ::
+
--
*Preconditions:*
`+cbegin() <= hint && hint <= cend()+`.

*Effects:*
Inserts copy of `value`.
Iterator `hint` is used as a suggestion where to start to search insert
position.

*Returns:*
Returns an iterator to the inserted element.
--

{empty} +

----
iterator insert(const_iterator hint, value_type&& value);
----
{empty} ::
+
--
*Preconditions:*
`+cbegin() <= hint && hint <= cend()+`.

*Effects:*
Inserts `value` using move semantics.
Iterator `hint` is used as a suggestion where to start to search insert
position.

*Returns:*
Returns an iterator to the inserted element.
--

{empty} +

----
template <typename P>
iterator insert(const_iterator hint, P&& value);
----
{empty} ::
+
--
*Preconditions:*
`+cbegin() <= hint && hint <= cend()+`.

*Effects:*
Inserts a new element into the container.
New element is constructed as `+value_type(std::forward<P>(value))+`.
Iterator `hint` is used as a suggestion where to start to search insert
position.

*Note:*
This overload participates in overload resolution only if
`+std::is_constructible<value_type, P&&>::value+` is `true`.

*Returns:*
Returns an iterator to the inserted element.
--

{empty} +

----
template <typename InputIt>
void insert(InputIt first, InputIt last);
----
{empty} ::
+
--
*Effects:*
Inserts elements from range `[first, last)`.

The call to this function is equivalent to:
----
while (first != last)
{
    insert(*first);
    ++first;
}
----

*Note:*
This overload participates in overload resolution only if `InputIt`
satisfies requirements of
https://en.cppreference.com/w/cpp/named_req/InputIterator[`LegacyInputIterator`].
--

{empty} +

----
void insert(std::initializer_list<value_type> ilist);
----
{empty} ::
+
--
*Effects:*
Inserts elements from initializer list `ilist`.

The call to this function is equivalent to:
----
insert(ilist.begin(), ilist.end());
----
--

{empty} +

=== erase

----
iterator erase(iterator pos);
iterator erase(const_iterator pos);
----
{empty} ::
+
--
*Preconditions:*
`+cbegin() <= pos && pos < cend()+`.

*Effects:*
Removes the element pointed by iterator `pos`.

*Returns:*
Iterator following the last removed element.
--

{empty} +

----
iterator erase(const_iterator first, const_iterator last);
----
{empty} ::
+
--
*Preconditions:*
`+cbegin() <= first && first <= last && last <= cend()+`.

*Effects:*
Removes the elements in the range `[first, last)`.

*Returns:*
Iterator following the last removed element.
--

{empty} +

----
size_type erase(const Key& key);
----
{empty} ::
+
--
*Effects:*
Removes all elements with the key equivalent to `key`.

*Returns:*
Number of elements removed.
--

{empty} +

----
template <typename K>
size_type erase(K&& x);
----
{empty} ::
+
--
*Effects:*
Removes all elements with key that compares equivalent to the value `x`.

*Note:*
This overload participates in overload resolution only if
`Compare::is_transparent` exists and is a valid type.
It allows calling this function without constructing an instance of `Key`.

*Returns:*
Number of elements removed.
--

{empty} +

=== swap

----
void swap(small_flat_multimap& other);
----
{empty} ::
+
--
*Preconditions:*
`+allocator_traits::propagate_on_container_swap::value || get_allocator() == other.get_allocator()+`.

*Effects:*
Exchanges the contents of the container with those of `other`.

*Complexity:*
Constant in the best case. Linear in `+this->size()+` plus linear in
`+other.size()+` in the worst case.
--

{empty} +

=== lower_bound

----
iterator       lower_bound(const Key& key);
const_iterator lower_bound(const Key& key) const;
----
{empty} ::
+
--
*Effects:*
Returns an iterator pointing to the first element with key that is
not less than `key`, or `end()` if such an element is not found.

*Complexity:*
Logarithmic in `size()`.
--

{empty} +

----
template <typename K>
  iterator       lower_bound(const K& x);
template <typename K>
  const_iterator lower_bound(const K& x) const;
----
{empty} ::
+
--
*Effects:*
Returns an iterator pointing to the first element with key that compares
not less to the value `x`, or `end()` if such an element is not found.

*Note:*
This overload participates in overload resolution only if
`Compare::is_transparent` exists and is a valid type.
It allows calling this function without constructing an instance of `Key`.

*Complexity:*
Logarithmic in `size()`.
--

{empty} +

=== upper_bound

----
iterator       upper_bound(const Key& key);
const_iterator upper_bound(const Key& key) const;
----
{empty} ::
+
--
*Effects:*
Returns an iterator pointing to the first element with key that is
greater than `key`, or `end()` if such an element is not found.

*Complexity:*
Logarithmic in `size()`.
--

{empty} +

----
template <typename K>
  iterator       upper_bound(const K& x);
template <typename K>
  const_iterator upper_bound(const K& x) const;
----
{empty} ::
+
--
*Effects:*
Returns an iterator pointing to the first element with key that compares
greater to the value `x`, or `end()` if such an element is not found.

*Note:*
This overload participates in overload resolution only if
`Compare::is_transparent` exists and is a valid type.
It allows calling this function without constructing an instance of `Key`.

*Complexity:*
Logarithmic in `size()`.
--

{empty} +

=== equal_range

----
std::pair<iterator, iterator>             equal_range(const Key& key);
std::pair<const_iterator, const_iterator> equal_range(const Key& key) const;
----
{empty} ::
+
--
*Effects:*
Returns a range containing all elements with the key that is equal
to `key`. +
The first iterator in pair points to the first element that is not less
than `key`, or `end()` if such an element does not exist. +
The second iterator in pair points to the first element that is greater
that `key`, or `end()` is such an element does not exist.

*Complexity:*
Logarithmic in `size()`.
--

{empty} +

----
template <typename K>
  std::pair<iterator, iterator>             equal_range(const K& x);
template <typename K>
  std::pair<const_iterator, const_iterator> equal_range(const K& x) const;
----
{empty} ::
+
--
*Effects:*
Returns a range containing all elements with the key that compares equal
to the value `x`. +
The first iterator in pair points to the first element that compares not less
to the value `x`, or `end()` if such an element does not exist. +
The second iterator in pair points to the first element that compares greater
to the value `x`, or `end()` is such an element does not exist.

*Note:*
This overload participates in overload resolution only if
`Compare::is_transparent` exists and is a valid type.
It allows calling this function without constructing an instance of `Key`.

*Complexity:*
Logarithmic in `size()`.
--

{empty} +

=== find

----
iterator       find(const Key& key);
const_iterator find(const Key& key) const;
----
{empty} ::
+
--
*Effects:*
Finds an element with key equivalent to `key`.
If there are several elements with key in the container, any of them may be
returned.

*Returns:*
If element is found, returns an iterator to that element.
If no such element is found, returns `end()`.

*Complexity:*
Logarithmic in `size()`.
--

{empty} +

----
template <typename K>
  iterator       find(const K& x);
template <typename K>
  const_iterator find(const K& x) const;
----
{empty} ::
+
--
*Effects:*
Finds an element with key that compares equivalent to the value `x`.
If there are several elements with key in the container, any of them may be
returned.

*Note:*
This overload participates in overload resolution only if
`Compare::is_transparent` exists and is a valid type.
It allows calling this function without constructing an instance of `Key`.

*Returns:*
If element is found, returns an iterator to that element.
If no such element is found, returns `end()`.

*Complexity:*
Logarithmic in `size()`.
--

{empty} +

=== count

----
size_type count(const Key& key) const;
----
{empty} ::
+
--
*Effects:*
Returns the number of elements with key equivalent to `key`.

*Complexity:*
Logarithmic in `size()` plus linear in the number of the elements found.
--

{empty} +

----
template <typename K>
size_type count(const K& x) const;
----
{empty} ::
+
--
*Effects:*
Returns the number of elements with key that compares equivalent to the
value `x`.

*Note:*
This overload participates in overload resolution only if
`Compare::is_transparent` exists and is a valid type.
It allows calling this function without constructing an instance of `Key`.

*Complexity:*
Logarithmic in `size()` plus linear in the number of the elements found.
--

{empty} +

=== contains

----
bool contains(const Key& key) const;
----
{empty} ::
+
--
*Effects:*
Returns `true` if the container contains an element with key equivalent
to `key`, otherwise returns `false`.

*Complexity:*
Logarithmic in `size()`.
--

{empty} +

----
template <typename K>
bool contains(const K& x) const;
----
{empty} ::
+
--
*Effects:*
Returns `true` if the container contains an element with the key that
compares equivalent to the value `x`, otherwise returns `false`.

*Note:*
This overload participates in overload resolution only if
`Compare::is_transparent` exists and is a valid type.
It allows calling this function without constructing an instance of `Key`.

*Complexity:*
Logarithmic in `size()`.
--

{empty} +

=== data

----
value_type*       data() noexcept;
const value_type* data() const noexcept;
----
{empty} ::
+
--
*Effects:*
Returns pointer to the underlying array serving as element storage.
The pointer is such that range `[data(), data() + size())` is always
a valid range, even if the container is empty. `data()` is not
dereferenceable if the container is empty.

*Complexity:*
Constant.
--

{empty} +

== Non-member functions

=== operator==

----
template <typename K, typename T, std::size_t N, typename C, typename A>
bool operator==
(
    const small_flat_multimap<K, T, N, C, A>& x,
    const small_flat_multimap<K, T, N, C, A>& y
);
----
{empty} ::
+
--
*Effects:*
Returns `true` if the contents of the `x` and `y` are equal, `false` otherwise.

The comparison is performed by `std::equal`.
This comparison ignores the container's ordering `Compare`.
--

{empty} +

=== operator!=

----
template <typename K, typename T, std::size_t N, typename C, typename A>
bool operator!=
(
    const small_flat_multimap<K, T, N, C, A>& x,
    const small_flat_multimap<K, T, N, C, A>& y
);
----
{empty} ::
+
--
*Effects:*
Returns `true` if the contents of the `x` and `y` are not equal, `false` otherwise.

The comparison is performed by `std::equal`.
This comparison ignores the container's ordering `Compare`.
--

{empty} +

=== operator<

----
template <typename K, typename T, std::size_t N, typename C, typename A>
bool operator<
(
    const small_flat_multimap<K, T, N, C, A>& x,
    const small_flat_multimap<K, T, N, C, A>& y
);
----
{empty} ::
+
--
*Effects:*
Returns `true` if the contents of the `x` are lexicographically less than
the contents of `y`, `false` otherwise.

The comparison is performed by `std::lexicographical_compare`.
This comparison ignores the container's ordering `Compare`.
--

{empty} +

=== operator>

----
template <typename K, typename T, std::size_t N, typename C, typename A>
bool operator>
(
    const small_flat_multimap<K, T, N, C, A>& x,
    const small_flat_multimap<K, T, N, C, A>& y
);
----
{empty} ::
+
--
*Effects:*
Returns `true` if the contents of the `x` are lexicographically greater than
the contents of `y`, `false` otherwise.

The comparison is performed by `std::lexicographical_compare`.
This comparison ignores the container's ordering `Compare`.
--

{empty} +

=== operator\<=

----
template <typename K, typename T, std::size_t N, typename C, typename A>
bool operator<=
(
    const small_flat_multimap<K, T, N, C, A>& x,
    const small_flat_multimap<K, T, N, C, A>& y
);
----
{empty} ::
+
--
*Effects:*
Returns `true` if the contents of the `x` are lexicographically less than
or equal to the contents of `y`, `false` otherwise.

The comparison is performed by `std::lexicographical_compare`.
This comparison ignores the container's ordering `Compare`.
--

{empty} +

=== operator>=

----
template <typename K, typename T, std::size_t N, typename C, typename A>
bool operator>=
(
    const small_flat_multimap<K, T, N, C, A>& x,
    const small_flat_multimap<K, T, N, C, A>& y
);
----
{empty} ::
+
--
*Effects:*
Returns `true` if the contents of the `x` are lexicographically greater than
or equal to the contents of `y`, `false` otherwise.

The comparison is performed by `std::lexicographical_compare`.
This comparison ignores the container's ordering `Compare`.
--

{empty} +

=== swap

----
template <typename K, typename T, std::size_t N, typename C, typename A>
void swap
(
    small_flat_multimap<K, T, N, C, A>& x,
    small_flat_multimap<K, T, N, C, A>& y
);
----
{empty} ::
+
--
*Effects:*
Swaps the contents of `x` and `y`. Calls `x.swap(y)`.
--

{empty} +

=== erase_if

----
template <typename K, typename T, std::size_t N, typename C, typename A,
          typename Predicate>
typename small_flat_multimap<K, T, N, C, A>::size_type
    erase_if(small_flat_multimap<K, T, N, C, A>& c, Predicate pred);
----
{empty} ::
+
--
*Effects:*
Erases all elements that satisfy the predicate `pred` from the container.

Parameter `pred` is unary predicate which returns `true` if the element should
be removed.

*Returns:*
The number of erased elements.
--

{empty} +

End of document.
